# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6a21\u677f\u540d')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7a0b\u5e8f\u8def\u5f84')),
                ('servers', models.ManyToManyField(to='cmdb.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('verify_time', models.DateTimeField(verbose_name='\u5ba1\u6838\u65f6\u95f4')),
                ('release_time', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('version_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('status', models.IntegerField(default=1, verbose_name='\u5de5\u5355\u72b6\u6001')),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_template', to='code_release.Release_template', verbose_name='\u5de5\u5355\u540d\u79f0')),
            ],
        ),
    ]
